language: node_js
node_js:
    - "6"
sudo: false
os:
  - linux
  - osx
branches:
  except:
  - master
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1600x1200x32 > /dev/null 2>&1 &
  - npm install
script:
  - npm run travis-build
  - npm test
