language: node_js
node_js:
    - "7"
os:
  - osx
  - linux
branches:
  except:
  - master
addons:
  apt:
    packages:
      - xvfb
before_script: 
  - "export DISPLAY=:99.0"
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sh -e /etc/init.d/xvfb start;fi
  - sleep 3
install:
  - npm install
script:
  - npm run json-server
  - npm run travis-build
  - npm test
  - npm run karma
notifications:
  email: false